# Generated by Django 3.0 on 2019-12-02 12:14

import Gig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, validators=[Gig.models.validate_date])),
                ('venue', models.CharField(default='TBA', max_length=100)),
                ('supports', models.TextField(blank=True, max_length=500, null=True)),
                ('time', models.TimeField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
